packages:
  - packages/*
  - packages/components-react/*
  - packages/components-css/*
  - packages/docs/*
  - packages/tokens/*

overrides:
  shell-quote@>=1.1.0 <=1.8.3: ">=1.8.4"
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  unrs-resolver: true
engineStrict: true
saveExact: true
savePrefix: ""
strictPeerDependencies: false
autoInstallPeers: false
provenance: true
